### ISSUE TITLE
Linking to subpages with data-rel="dialog" doesn't work

### ISSUE THREAD

**Issue by adammessinger** [ToddThomson/jQuery-Mobile-Subpage-Widget#1]
I've created a work-around for this that uses a new subpage-dialog role to determine what gets shown as a dialog and what doesn't. Not sure if that's the best way to do it since I was figuring out the jQM internals as I went, but it works. Interested in a patch?

**Comment by ToddThomson** [comment]
Thanks Adam. Send me the patch and I'll take a look at it. I use the subpage widget extensively with jQuery Mobile, but I've not yet used it to reference a dialog subpage (although I do see a need for it).

**Comment by ToddThomson** [comment]
Thanks Adam, I will review and test early next week.

**Comment by ToddThomson** [comment]
Pull request made.
