### ISSUE TITLE
Origin null is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by donglongfei** [ToddThomson/jQuery-Mobile-Subpage-Widget#10]
I got the error : "XMLHttpRequest cannot load file://localhost/test/www/subpages.html. Origin null is not allowed by Access-Control-Allow-Origin." when using jquery.mobile.subpage.js.

I'm not sure why there is access-control-allow-origin error since all of pages should be read locally. BTW, i'm using emulator to test.
thanks.

**Comment by ToddThomson** [comment]
Please attempt to debug and diagnose errors in your app before submitting an issue. I'm sorry, but there is no possible way I can help you with the specific error you have in your app.
