### ISSUE TITLE
Change page programmatically with dialog type subpage 

### ISSUE THREAD

**Issue by michelpa** [ToddThomson/jQuery-Mobile-Subpage-Widget#13]
All is in the title. I cannot change page with code to a dialog subpage. It seems that $.mobile.changePage() does not work. Any idea? I nees to do some check in js before opening the dialog...

**Comment by ToddThomson** [comment]
@michelpa I do not have enough information to move forward on this issue. Do you have some code that I can reference that shows the problem?

**Comment by ToddThomson** [comment]
@michelpa If this is still an issue for you please let me know.
I'm closing this issue as I don't have enough info to move forward.

**Comment by michelpa** [comment]
I will test with new version and give you more explanation about the issue if it still here. But it will be only in a few week... TKS
