### ISSUE TITLE
FOUC when loading subpage-dialog

### ISSUE THREAD

**Issue by chrisstephens** [ToddThomson/jQuery-Mobile-Subpage-Widget#14]
I get a flash of unstyled content when I load subpage-dialog. The unstyled content is the dialog's markup.

I've tried various things to suppress it (adding and removing ui-mobile-rendering to html on different events) but no luck so far.

Happy to try out any suggestions you may have!

(Great plugin, btw. Thanks!)

**Comment by ToddThomson** [comment]
@chrisstephens Thanks for this. Can you provide a test page so I can recreate the issue. Also what device and browser are you testing with?

**Comment by chrisstephens** [comment]
Ah. When I strip the code back to submit to this ticket I seem not to get
the FOUC. I'll build it back up and see what makes it re-appear...

On Sat, Jun 9, 2012 at 12:30 AM, Todd Thomson <
reply@reply.github.com

**Comment by ToddThomson** [comment]
Closing due to no follow up for many months.
