### ISSUE TITLE
(Endless) loop when submitting form via AJAX

### ISSUE THREAD

**Issue by niksy** [ToddThomson/jQuery-Mobile-Subpage-Widget#16]
When you try to submit form which is placed inside subpage via default AJAX interface, which submits to the URL of the original page which contains that subpage, page refreshes almost endlessly depending on the number of times you used form to submit data. Is this a know limitation?

**Comment by ToddThomson** [comment]
Hi Ivan,

Please post a link to a test example where I can see this behavoir.

Cheers, Todd

**Comment by niksy** [comment]
Huh, seems like it was some page event from my application which was clashing with plugin. If I encounter this problem anymore, I will reopen this issue.
