### ISSUE TITLE
1st Subpage does not get back button using data-add-back-btn="true"

### ISSUE THREAD

**Issue by bluescrubbie** [ToddThomson/jQuery-Mobile-Subpage-Widget#18]
Hi Todd,
Thanks for this widget - it's been essential for dynamic sites.
I've found an issue when adding back buttons to subpages.

I've got two subpages within a page.  Each subpage has the attribute:
    data-add-back-btn="true".
The first page doesn't get the back button, the second does.

Here's a jsfiddle that demonstrates it: http://jsfiddle.net/bluescrubbie/aEPPL/2/
The same code set up as separate pages works: http://jsfiddle.net/bluescrubbie/pqzzp/2/

notes: 
- The listview ul/li is there for convenience - it still happens if you take it out.
- If you wish, you can find less stripped down versions if you go back earlier fiddle versions.

**Comment by bluescrubbie** [comment]
Still happeing on version 1.3 on JQM 1.3.1.
I found it works if I change subpage to self init on pagecreate instead of pagebeforecreate.  Seems a timing issue.

**Comment by ToddThomson** [comment]
@bluescrubbie Subpage widget now auto initializes using pagecreate.
