### ISSUE TITLE
Can't auto-show first sub-page.

### ISSUE THREAD

**Issue by joshmouch** [ToddThomson/jQuery-Mobile-Subpage-Widget#19]
I'd like for the first sub-page to automatically show itself when the page loads.  For the life of me, I can't find a way to do this consistently.

My setup is:
Page A has link to Page B
Page B has several subpages (e.g. SubPage 1, SubPage 2).  It also has a link back to Page A.

So first, I can get the "default sub-page" working if I browse directly to "Page B" (so that Page A was not hit first). I  add some script to the page's "pageinit" event:

$(document).delegate("#PAGEA", "pageinit", function (event, data) {
    $.mobile.changePage("#SUBPAGE1");
});

Note that if I add it to the subpage's pageinit event, it gets called waaaaaay too often.  The behavior is too sporadic for me to nail down.

But second, if I browse to "Page A" first, and then click the link to "Page B", my script runs, but it doesn't actually show SubPage1.

I've tried every combination of pageinit and pagechange events on both "Page A" and "SubPage 1", and nothing works.

However, I can get my code to select SubPage1 if I click around enough.  Again, this is too sporadic for me to nail down.  But it has something to do with the URL portion before the hash ("#") changing.

Based on my observation in the above paragraph, I could conclude that I can only set the default subpage if the URL before the hash is whatever it was on the first page hit.

**Comment by ToddThomson** [comment]
Hi Josh, I'm really not sure what you are trying to do. The subpage widget is quite simple and is meant to address only 1 thing: pages loaded via jQM ajax navigation only support a single page. The subpage widget allows multiple subpages to be loaded with a single load.
If you want a specific "subpage" to be the first to load then make it the "page" and have all the other subpages be within the page container.

**Comment by joshmouch** [comment]
Well, I'm trying to make a wizard-like control.  To do so, I have a server-side helper method that generates the markup for each step.  The code I have now is very elegant and easy to read: one method call for each step you want added to the wizard.  It also handles a lot of things: generating subpage markup, generating menu items, etc.

While your suggestion would work, I don't think I could modify the server-side code to put the markup from X-1 steps inside the first step without making a complete mess of my code.

After lot of experimentation, I mostly got this working, though the URLs that end up in the address bar are inconsistent.  Also, it's weird that in one method I have to pass a jQuery selector to $.mobile.changePage and in the other, I have to pass a jQuery object.  Any other configuration I've tried won't work.  Here's my current psuedo-code:

$(document).live("pageinit", function() {
  $.mobile.changePage("#SubPage1");

  $(document).live("pagebeforechange", "#PageB", function() {
    if (the event target is not "#PageB") return;
    if (data.toPage[0].id == "#SubPage1") return;
    var defaultSubPage = $("#SubPage1");
    data.toPage = defaultSubPage;
  });
});

**Comment by joshmouch** [comment]
Are you willing to open this back up, considering your solution doesn't lend itself well to server-side generated markup?

**Comment by ToddThomson** [comment]
The subpage widget is involved only in JQM AJAX page loads. It simply looks at the parent "page" container of the AJAX page being loaded and looks for "subpages". All "subpages" found are inserted then inserted into the DOM as "pages" that can be navigated to.
If you can tell me specifically that there is an issue with the subpage widget then I will fix it in a timely manner. I cannot just change the code to fit your needs.
You can always fork the code and change it to meet your needs!

**Comment by joshmouch** [comment]
Well, there is a bug, so I'm not changing anything to meet my needs.  But I don't know if it's jQuery Mobile or this subpage plugin.
To wrap it succinctly: $.mobile.changePage() doesn't work as expected in subpage event handlers.

I understand if you don't want to look into this... I just figured since this project is linked to directly from jQuery mobile's documentation, that it would be willing to me a more generalized plugin.

I'll probably just find some other way to implement wizard controls.

**Comment by ToddThomson** [comment]
Hi Josh, you need to document a specific issue with the subpage widget regarding how it fails in its stated function. Please provide a simple test app to reproduce the issue.
Right now your wizard control is not working, however, it is not up to me to find out what the problem is - pin point the problem and if it is in the subpage widget, I will attempt to fix it ( or provide a patch and contribute to the project ).
