### ISSUE TITLE
Can't detect JQM version.

### ISSUE THREAD

**Issue by joshmouch** [ToddThomson/jQuery-Mobile-Subpage-Widget#23]
Line #51 has the following:

if ($.mobile.version >= 1.3) {

However, on my system. this returns false because $.mobile.version == "1.3.0".

**Comment by ronlussier** [comment]
[Pull Request 25](https://github.com/ToddThomson/jQuery-Mobile-Subpage-Widget/pull/25).  My apologies

**Comment by ToddThomson** [comment]
Thanks Ron, Josh.
