### ISSUE TITLE
Invalid reference.

### ISSUE THREAD

**Issue by joshmouch** [ToddThomson/jQuery-Mobile-Subpage-Widget#24]
Line #67 has:

t._createSubPage();

which should be:

self._createSubPage();

**Comment by ronlussier** [comment]
Weird, I thought I addressed that, but it looks like I forgot to put it in the right repository.  I'll check it in and do a pull request.

**Comment by ronlussier** [comment]
[Pull Request 25](https://github.com/ToddThomson/jQuery-Mobile-Subpage-Widget/pull/25).  My apologies.

**Comment by ToddThomson** [comment]
No worries Ron. Thanks for your involvement!
