### ISSUE TITLE
How to create nested pages

### ISSUE THREAD

**Issue by siva12** [ToddThomson/jQuery-Mobile-Subpage-Widget#28]
I just want to create a nested page structure like

![2](https://f.cloud.github.com/assets/6115220/1683716/e16440ca-5dc1-11e3-9e65-72b26a69a4b6.jpg)

The first sub page works fine here but the second sub page is not working.

Sample code here:

![1](https://f.cloud.github.com/assets/6115220/1683848/7d9b753e-5dc3-11e3-8cfb-63cf061fa900.jpg)

**Comment by ToddThomson** [comment]
There is no need to nest a subpage within a subpage. Stack the subpages within the page.
