### ISSUE TITLE
with jqm 1.4.0

### ISSUE THREAD

**Issue by zirho** [ToddThomson/jQuery-Mobile-Subpage-Widget#30]
it's with error like this

Uncaught TypeError: Object [object Object] has no method 'enhanceWithin' 

it works fine with 1.3.2

am i the only one who use 1.4.0?

as of 1.4, jqm doesn't need it anymore?

**Comment by zirho** [comment]
![screen shot 2014-01-16 at 2 33 33 am](https://f.cloud.github.com/assets/1251296/1929570/b9180bd0-7e99-11e3-8e09-24af35f669bb.png)
![screen shot 2014-01-16 at 2 33 40 am](https://f.cloud.github.com/assets/1251296/1929571/b918c8c2-7e99-11e3-97a6-708e94c7f056.png)

here is the codes

index.html

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.css" />
        <title>page1</title>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js"></script>
        <script type="text/javascript" src="jquery.mobile.subpage.js"></script>

```
</head>
<body>
    <div data-role="page" class="" id="page1" data-title="page1">
        <div data-role="header" data-position="fixed">
            <h1>page1</h1>
        </div>
        <div role="main" class="ui-content">
            <ul data-role="listview" data-inset="true" data-divider-theme="a">
                <li data-role="list-divider">pages </li>
                <li><a href="index2.html">page2</a></li>
            </ul>
        </div>
    </div>
</body>
```

</html>

index2.html

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.css" />
        <title>page2</title>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js"></script>
        <script type="text/javascript" src="jquery.mobile.subpage.js"></script>
    </head>
    <body>

```
<div id="page2" data-role="page">

    <!--sub page-->
    <div data-role="subpage" id="page2_1">
        <div data-role="header" data-position="fixed">
            <h1>page 2 - 1</h1>
            <a data-rel="back" href="#" data-icon="arrow-l" data-direction="reverse" class="alt ui-btn-left">Back</a>
        </div>
        <div data-role="content">
            page 2 - 1
        </div>
    </div>

    <!--main page-->
    <div data-role="header" data-position="fixed">
        <h1>page 2</h1>
        <a data-rel="back" href="#info-page" data-icon="arrow-l" data-direction="reverse" class="ui-btn-left">Back</a>
    </div>
    <div data-role="content">
        <ul data-role="listview" data-inset="true">
            <li>
            <a href="#page2_1">About</a>
            </li>
        </ul>
    </div>
</div>
```

</body>
</html>

**Comment by ToddThomson** [comment]
I have not yet updated the subpage widget for jQM 1.4.

**Comment by zirho** [comment]
Oh okay!

Thank you for the nice work! I use it with 1.3.x for a while then!

**Comment by ToddThomson** [comment]
Sorry for the delay. I update this widget when necessary for my apps based on jQuery Mobile.
