### ISSUE TITLE
interlink between any two subpages?

### ISSUE THREAD

**Issue by thelinjin** [ToddThomson/jQuery-Mobile-Subpage-Widget#4]
I saw this comment by ganeshbanoth on the issue of interlink between any two subpages. I've encountered the same problem as well. Can each page have only one subpage?

**Comment by ToddThomson** [comment]
Each <div> with data-role="page" can have more than 1 subpage. Subpages do not support subpages.
If you have a specific example of an error condition when using the subpages widget, please send me the example code which shows the error.
