### ISSUE TITLE
doesn´t work

### ISSUE THREAD

**Issue by kreacomunicacion** [ToddThomson/jQuery-Mobile-Subpage-Widget#5]
Hi!!
This widget doesn´t work for my app. I put the js archive in my head of the page and I changed the data-role to subpage. But doesn´t work.
All the subpages loads at the same time on the parents page and the css is missing. I´m doing something wrong? 

We are using iscroll is that a problem??

Thank you in advance.

**Comment by ToddThomson** [comment]
The subpage widget is really simple to use: within the html returned by the ajax call (div data-role="page"), add your subpages which start with (div data-role="subpage").
Without any submitted code, or a reference to your code, I can't guess what your mistakes are. iScroll is not an issue.

**Comment by kreacomunicacion** [comment]
These two pages together form a test to illustrate the problem. the css archive of the subpages no load.
Please say me what is the problem or what I´m doing wrong.
The two pages are:

http://www.kreacomunicacion.com/jqm/home.html

http://www.kreacomunicacion.com/jqm/segunda.html

I´m desperate it´s my first app with jquery mobile.

Thank you in advance.

**Comment by ToddThomson** [comment]
I took a very quick look at your code. The initial entry to a jQM site loads and processes the tags in the head tag ( CSS, script, etc. ) and all "role=page" divs in the body tag ( you will need to re-read the jQM documentation and go through the learning curve on how to utilize jQM ).
The subpage widget allows you to get around a limitation of jQM where the the loadPage() will only process a single div with the role=page.
Good luck with your application.
