### ISSUE TITLE
Not sure if I'm coding wrong or what...

### ISSUE THREAD

**Issue by jcwhite2** [ToddThomson/jQuery-Mobile-Subpage-Widget#6]
I'm trying to incorporate the Subpage Widget into my jQm app, but I'm not having any luck. I thought I understood things correctly that I add the script, then add subpages to pages, like so,

``` html
<html>
 <head>
  <script jQuery.js>
  <script subpage.js>
  <script jQm.js>
 </head>
 <body>
  <div data-role="page">
   page 1
   <div data-role="subpage">
    subpage 1
   </div>
   <div data-role="subpage">
    subpage 2
   </div>
  </div>
  <div data-role="page">
   page 2
   <div data-role="subpage">
    subpage 1
   </div>
   <div data-role="subpage">
    subpage 2
   </div>
  </div>
 </body>
</html>
```

Is it not this simple?

**Comment by ToddThomson** [comment]
jQM has no problems loading multiple "pages" into the body container. It is only with through links loaded with ajax that jQM only loads a single "page". When loading a link to a page with ajax you can utilize the subpage widget to load any number of subpages that are contained within the single parent page. It is that simple.
