### ISSUE TITLE
On trying to link to the subpage, it goes to previous page

### ISSUE THREAD

**Issue by vijeta** [ToddThomson/jQuery-Mobile-Subpage-Widget#7]
I am not sure if I have coded correctly. Could you please help me out.
I have included your subpages.js in my app. 

And the page with multiple subpages, looks like this. 

```
  <div data-role="page" id="index1">
  <div data-role="header">
      <h6>Welcome...</h6>
      </div>
    <div data-role="content">
       <a href="#vj1">Go to subPage 1</a>
    </div>
    <div data-role="subpage" id="vj1">
        <div data-role="header">
        <h6>Welcome...</h6>
        </div>
         ...
         ...
   </div>
 </div>
```

On clicking on the "Go to subpage 1" link, it takes me to the previous page.  This was the same behavior I experienced before knowing that link to multipage document with Ajax navigation active will load only the first page. 

Please help.

**Comment by ToddThomson** [comment]
No issue found.
