### ISSUE TITLE
How have I to come back to the main page?

### ISSUE THREAD

**Issue by linocastrovilli** [ToddThomson/jQuery-Mobile-Subpage-Widget#8]
I've created subpages like you've shown

<div data-role="page" id="main">
...
...
<div data-role="subpage" id="sub">
</div>

</div>

Now, if the user is in the subpage called "sub", how can he come back to the main page? I've tried with <a href="#main"> but it doesn't work...

Thank for the good widget

**Comment by facatalan** [comment]
I have the same question, how to link main page from a subpage? ...without "back".
Thanks!
