### ISSUE TITLE
Example site not mobile

### ISSUE THREAD

**Issue by brinman** [ToddThomson/jQuery-Mobile-Subpage-Widget#9]
Is anyone else unable to get the example site (integra-international.com) to show in mobile view?  I've tried with a user-agent switcher and also with a native mobile phone (android based) and it's not displaying a mobile-specific view.

**Comment by ToddThomson** [comment]
Sorry, a deployment to the production server missed a critical file and thus the mobile view engine was not updated properly.

The mobile site should be working correctly now.

**Comment by ToddThomson** [comment]
The mobile site has been changed to:

http://m.integra-international.net
